Vagrant.configure("2") do |config|
  config.vm.guest = :ubuntu
  config.vm.box_url = "https://atlas.hashicorp.com/ubuntu/boxes/trusty64"
  config.vm.box = "ubuntu/trusty64"
  config.vm.network  "private_network", ip: "192.168.33.13"
  config.vm.hostname = "crypt-lab3-minion.fh-koeln.de"

  # config.vm.network "public_network"
  # Use NFS as a shared folder
  config.vm.synced_folder ".", "/home/vagrant/code/"

  config.vm.provider :virtualbox do |vb|
    # vb.customize ["startvm", :id, "--type", "gui"]
    vb.name = "crypt-lab3-minion"
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
  end
  
  #config.vm.provision "shell", path: "script.sh"
  
   #config.vm.network "forwarded_port", guest: 80, host: 8000

end